\ TEMPLATE FILE for STM32F103xx
\ created by svdcutter for Mecrisp-Stellaris Forth by Matthias Koch
\ sdvcutter  takes a CMSIS-SVD file plus a hand edited config.xml file as input 
\ By Terry Porter "terry@tjporter.com.au", released under the GPL V2 Licence
\   Modified by juju2013@github - 2020


compiletoflash
$40006C04 constant BKP ( Backup registers ) 
BKP $0 + constant BKP-DR1 ( Backup data register BKP_DR ) 
BKP $4 + constant BKP-DR2 ( Backup data register BKP_DR ) 
BKP $8 + constant BKP-DR3 ( Backup data register BKP_DR ) 
BKP $C + constant BKP-DR4 ( Backup data register BKP_DR ) 
BKP $10 + constant BKP-DR5 ( Backup data register BKP_DR ) 
BKP $14 + constant BKP-DR6 ( Backup data register BKP_DR ) 
BKP $18 + constant BKP-DR7 ( Backup data register BKP_DR ) 
BKP $1C + constant BKP-DR8 ( Backup data register BKP_DR ) 
BKP $20 + constant BKP-DR9 ( Backup data register BKP_DR ) 
BKP $24 + constant BKP-DR10 ( Backup data register BKP_DR ) 
BKP $3C + constant BKP-DR11 ( Backup data register BKP_DR ) 
BKP $40 + constant BKP-DR12 ( Backup data register BKP_DR ) 
BKP $44 + constant BKP-DR13 ( Backup data register BKP_DR ) 
BKP $48 + constant BKP-DR14 ( Backup data register BKP_DR ) 
BKP $4C + constant BKP-DR15 ( Backup data register BKP_DR ) 
BKP $50 + constant BKP-DR16 ( Backup data register BKP_DR ) 
BKP $54 + constant BKP-DR17 ( Backup data register BKP_DR ) 
BKP $58 + constant BKP-DR18 ( Backup data register BKP_DR ) 
BKP $5C + constant BKP-DR19 ( Backup data register BKP_DR ) 
BKP $60 + constant BKP-DR20 ( Backup data register BKP_DR ) 
BKP $64 + constant BKP-DR21 ( Backup data register BKP_DR ) 
BKP $68 + constant BKP-DR22 ( Backup data register BKP_DR ) 
BKP $6C + constant BKP-DR23 ( Backup data register BKP_DR ) 
BKP $70 + constant BKP-DR24 ( Backup data register BKP_DR ) 
BKP $74 + constant BKP-DR25 ( Backup data register BKP_DR ) 
BKP $78 + constant BKP-DR26 ( Backup data register BKP_DR ) 
BKP $7C + constant BKP-DR27 ( Backup data register BKP_DR ) 
BKP $80 + constant BKP-DR28 ( Backup data register BKP_DR ) 
BKP $84 + constant BKP-DR29 ( Backup data register BKP_DR ) 
BKP $88 + constant BKP-DR30 ( Backup data register BKP_DR ) 
BKP $8C + constant BKP-DR31 ( Backup data register BKP_DR ) 
BKP $90 + constant BKP-DR32 ( Backup data register BKP_DR ) 
BKP $94 + constant BKP-DR33 ( Backup data register BKP_DR ) 
BKP $98 + constant BKP-DR34 ( Backup data register BKP_DR ) 
BKP $9C + constant BKP-DR35 ( Backup data register BKP_DR ) 
BKP $A0 + constant BKP-DR36 ( Backup data register BKP_DR ) 
BKP $A4 + constant BKP-DR37 ( Backup data register BKP_DR ) 
BKP $A8 + constant BKP-DR38 ( Backup data register BKP_DR ) 
BKP $AC + constant BKP-DR39 ( Backup data register BKP_DR ) 
BKP $B0 + constant BKP-DR40 ( Backup data register BKP_DR ) 
BKP $B4 + constant BKP-DR41 ( Backup data register BKP_DR ) 
BKP $B8 + constant BKP-DR42 ( Backup data register BKP_DR ) 
BKP $28 + constant BKP-RTCCR ( RTC clock calibration register  BKP_RTCCR ) 
BKP $2C + constant BKP-CR ( Backup control register  BKP_CR ) 
BKP $30 + constant BKP-CSR ( BKP_CSR control/status register  BKP_CSR ) 
