\ load register variables
include FSMC.fs
include PWR.fs
include RCC.fs
include GPIOA.fs
include GPIOB.fs
include GPIOC.fs
include GPIOD.fs
include GPIOE.fs
include GPIOF.fs
include GPIOG.fs
include AFIO.fs
include EXTI.fs
include DMA1.fs
include DMA2.fs
include SDIO.fs
include RTC.fs
include BKP.fs
include IWDG.fs
include WWDG.fs
include TIM1.fs
include TIM8.fs
include TIM2.fs
include TIM3.fs
include TIM4.fs
include TIM5.fs
include TIM9.fs
include TIM12.fs
include TIM10.fs
include TIM11.fs
include TIM13.fs
include TIM14.fs
include TIM6.fs
include TIM7.fs
include I2C1.fs
include I2C2.fs
include SPI1.fs
include SPI2.fs
include SPI3.fs
include USART1.fs
include USART2.fs
include USART3.fs
include ADC1.fs
include ADC2.fs
include ADC3.fs
include CAN.fs
include DAC.fs
include DBG.fs
include UART4.fs
include UART5.fs
include CRC.fs
include FLASH.fs
include NVIC.fs
include USB.fs
